class EthiopianCities {
  static const List<String> cities = [
    'Addis Ababa',
    'Adama',
    'Gondar',
    'Mek\'ele',
    'Hawassa',
    'Bahir Dar',
    'Dire Dawa',
    'Dessie',
    'Jimma',
    'Jijiga',
    'Shashamane',
    'Bishoftu',
    'Sodo',
    'Arba Minch',
    'Hosaena',
    'Dilla',
    'Nekemte',
    'Debre Birhan',
    'Asella',
    'Debre Mark\'os',
    'Kombolcha',
    'Debre Tabor',
    'Adigrat',
    'Weldiya',
    'Sebeta',
    'Burayu',
    'Shire Inda Selassie',
    'Gambela',
    'Bale Robe',
    'Butajira',
    'Ziway',
    'Areka',
    'Yirgalem',
    'Wolaita Sodo',
    'Mizan Teferi',
    'Boditi',
    'Goba',
    'Hageremariam',
    'Deder',
    'Korem',
    'Metu',
    'Wukro',
    'Ambo',
    'Alaba Kulito',
    'Modjo',
    'Chiro',
    'Ginchi',
    'Fiche',
    'Gimbi',
    'Tulu Bolo',
    'Kofele',
    'Bonga',
    'Gidole',
    'Sawla',
    'Mojo',
    'Holeta',
    'Sendafa',
    'Sululta',
    'Legetafo',
    'Gelanda',
    'Dukem',
    'Alem Gena',
    'Asosa',
    'Semera',
    'Logia',
    'Mille',
    'Dubti',
    'Chifra',
    'Aysaita',
    'Afambo',
    'Teru',
    'Yallo',
    'Gulina',
    'Ewa',
    'Awra',
    'Gollina',
    'Argobba',
    'Dalifage',
    'Gewane',
    'Amibara',
    'Awash Sebat Kilo',
    'Dulecha',
    'Argoba',
    'Artemu',
    'Bure',
    'Dembecha',
    'Finote Selam',
    'Kossober',
    'Injibara',
    'Dangila',
    'Chagni',
    'Pawe',
    'Guba',
    'Manasibu',
    'Mendi',
    'Boila',
    'Nedjo',
    'Kiltu Kara',
    'Guliso',
    'Ayira',
    'Yubdo',
    'Dembi Dolo',
    'Mugi',
    'Anfillo',
    'Gidami',
    'Begie',
    'Tongi',
    'Bedele',
    'Arjo',
    'Agaro',
    'Limmu Genet',
    'Seka',
    'Shebe',
    'Gera',
    'Sigmo',
    'Setema',
    'Gumay',
    'Kersa',
    'Omo Nada',
    'Dedo',
    'Tiro Afeta',
    'Sokoru',
    'Limmu Kosa',
    'Chora Botor',
    'Mana',
    'Bono Bedele',
    'Gechi',
    'Dabo Hana',
    'Bilo Nopha',
    'Yayu',
    'Hurumu',
    'Metu Zuria',
    'Darimu',
    'Alge Sachi',
    'Didu',
    'Becho',
    'Tole',
    'Goro',
    'Woliso',
    'Wenchi',
    'Dano',
    'Nonno',
    'Jibat',
    'Ambo Zuria',
    'Toke Kutaye',
    'Dendi',
    'Jeldu',
    'Ginde Beret',
    'Abuna Ginde Beret',
    'Meta Robi',
    'Mersa',
    'Woldiya',
    'Kobo',
    'Lalibela',
    'Kulmesk',
    'Muja',
    'Gashena',
    'Kon',
    'Nifas Mewcha',
    'Debre Tabor',
    'Wereta',
    'Hamusit',
    'Addis Zemen',
    'Ebinat',
    'Adet',
    'Merawi',
    'Tis Abay',
    'Zegie',
    'Gorgora',
    'Chuaht',
    'Koladiba',
    'Azezo',
    'Metemma',
    'Humera',
    'Sheraro',
    'Aksum',
    'Adwa',
    'Inda Selassie',
    'Enticho',
    'Rama',
    'Bizet',
    'Hagere Selam',
    'Abiy Addi',
    'Maychew',
    'Korem',
    'Alamata',
    'Mehoni',
    'Maichew',
    'Hiwane',
    'Quiha',
    'Wukro',
    'Freweyni',
    'Adigrat',
    'Zalambessa',
    'Irob',
    'Gulomahda',
    'Ganta Afeshum',
    'Saesi Tsaedaemba',
    'Kilte Awulaelo',
    'Hawzen',
    'Degua Tembien',
    'Inderta',
    'Hintalo Wajirat',
    'Saharti Samre',
    'Ofla',
    'Endamehoni',
    'Alaje',
    'Raya Azebo',
    'Raya Alamata',
  ];
}
